name: AU PROD Schedule PPV

on:
  workflow_dispatch:
    inputs:
      RUNNER_TYPE:
        description: 'Choose Runner Architecture (ARM64 for Hari, X64 for SriDevi)'
        required: true
        default: 'ARM64'
        type: choice
        options:
          - ARM64
          - X64

      PPV_CONFIG:
        description: 'PPV config filename/key'
        required: true
        default: 'aj_joshua_prenga.json'

      PAYMENT_METHOD:
        description: 'Payment method'
        required: true
        default: 'credit_card'
        type: choice
        options:
          - credit_card
          - gpay

      SWITCH:
        description: 'Switch to Ultimate'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

permissions:
  contents: read

jobs:
  prod:
    name: PROD | ${{ matrix.plan }}

    runs-on:
      - self-hosted
      - macOS
      - ${{ inputs.RUNNER_TYPE }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        plan:
          - standard_monthly
          - standard_apm
          - ultimate_apm
          - ultimate_upfront

    env:
      CI: 'true'
      HEADLESS: 'true'
      DAZN_REGION: AU
      DAZN_ENV: prod
      SOURCE: schedule
      PLAN: ${{ matrix.plan }}
      PPV_CONFIG: ${{ inputs.PPV_CONFIG }}
      PAYMENT_METHOD: ${{ inputs.PAYMENT_METHOD }}
      SWITCH: ${{ inputs.SWITCH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Runner
        run: |
          echo "Runner: $RUNNER_NAME"
          echo "OS: $RUNNER_OS"
          hostname

      - name: Verify Node
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          rm -rf node_modules
          npm ci

      - name: Verify Playwright
        run: npx playwright --version

      - name: Run PROD PPV Flow
        run: npx playwright test tests/new_user/newuser.ppv.spec.ts --project=chromium

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-schedule-${{ github.run_id }}-${{ github.job }}
          path: playwright-report/
          if-no-files-found: ignore

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-schedule-${{ github.run_id }}-${{ github.job }}
          path: |
            test-results/
            reports/
          if-no-files-found: ignore
